apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app-deployment
spec:
  replicas: 2  # Number of pod replicas
  selector:
    matchLabels:
      app: streamlit-app
  template:
    metadata:
      labels:
        app: streamlit-app
    spec:
      containers:
      - name: streamlit-app-container
        image: your-dockerhub-username/streamlit-app:latest  # Replace with your Docker image
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-app-service
spec:
  selector:
    app: streamlit-app
  ports:
    - protocol: TCP
      port: 80  # External port
      targetPort: 8501  # Streamlit app port in container
  type: LoadBalancer  # Change to NodePort if you don't have a cloud load balancer
